import 'mayoreo_data_store.dart';

const MayoreoCatalogSnapshot
kMayoreoSeedCatalogSnapshot = MayoreoCatalogSnapshot(
  companies: <MayoreoCatalogCompanyRecord>[
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_1',
      code: 'BIO_PAPPEL',
      name: 'BIO PAPPEL',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_2',
      code: 'DESPERDICIOS_QUERETANA',
      name: 'DESPERDICIOS QUERETANA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_3',
      code: 'DESPERDICIOS_QUERETANA_CRISTO',
      name: 'DESPERDICIOS QUERETANA CRISTO',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_4',
      code: 'DESPERDICIOS_QUERETANA_MICHEL',
      name: 'DESPERDICIOS QUERETANA MICHEL',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_5',
      code: 'DESPERDICIOS_QUERETANA_SAN_LUIS',
      name: 'DESPERDICIOS QUERETANA SAN LUIS',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_6',
      code: 'DESPERDICIOS_QUERETANA_SAN_PABLO',
      name: 'DESPERDICIOS QUERETANA SAN PABLO',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_7',
      code: 'DICDI_PROYECTOS',
      name: 'DICDI PROYECTOS',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_8',
      code: 'EL_PALOMAR',
      name: 'EL PALOMAR',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_9',
      code: 'EL_PALOMAR_GUADALAJARA',
      name: 'EL PALOMAR GUADALAJARA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_10',
      code: 'FANOSA',
      name: 'FANOSA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_11',
      code: 'FERNANDO_RUBIO',
      name: 'FERNANDO RUBIO',
      contact: '',
      active: false,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_12',
      code: 'GRUPAK',
      name: 'GRUPAK',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_13',
      code: 'IGNACIO_MELGOZA',
      name: 'IGNACIO MELGOZA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_14',
      code: 'JAIME_VELAZQUEZ',
      name: 'JAIME VELAZQUEZ',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_15',
      code: 'JOSE_RODRIGUEZ',
      name: 'JOSE RODRIGUEZ',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_16',
      code: 'KS',
      name: 'KS',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_17',
      code: 'MAC',
      name: 'MAC',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_18',
      code: 'MAJOSE',
      name: 'MAJOSE',
      contact: '',
      active: false,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_19',
      code: 'MAJOSE_SUACERO',
      name: 'MAJOSE SUACERO',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_20',
      code: 'MAJOSE_YAIR',
      name: 'MAJOSE YAIR',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_21',
      code: 'MONROE_MEXICO',
      name: 'MONROE MEXICO',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_22',
      code: 'NORMA_CASTILLO',
      name: 'NORMA CASTILLO',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_23',
      code: 'PLEXA',
      name: 'PLEXA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_24',
      code: 'RAQSA',
      name: 'RAQSA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_25',
      code: 'RICARDO_GARCIA_MENDIETA',
      name: 'RICARDO GARCIA MENDIETA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_26',
      code: 'SERVIN',
      name: 'SERVIN',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_27',
      code: 'SETEX',
      name: 'SETEX',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_28',
      code: 'SRA_RITA',
      name: 'SRA RITA',
      contact: '',
      active: true,
      notes: '',
    ),
    MayoreoCatalogCompanyRecord(
      id: 'co_seed_29',
      code: 'YOROZU',
      name: 'YOROZU',
      contact: '',
      active: true,
      notes: '',
    ),
  ],
  materials: <MayoreoCatalogMaterialRecord>[
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_1',
      code: 'ORDINARIO_DE_PRIMERA_RECOGIDO',
      level: 'GENERAL',
      name: 'ORDINARIO DE PRIMERA RECOGIDO',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_1',
      code: 'ORDINARIO_DE_PRIMERA_RECOGIDO',
      level: 'COMERCIAL',
      name: 'ORDINARIO DE PRIMERA RECOGIDO',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_1',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_2',
      code: 'PAPEL_ARCHIVO',
      level: 'GENERAL',
      name: 'PAPEL ARCHIVO',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_2',
      code: 'PAPEL_ARCHIVO',
      level: 'COMERCIAL',
      name: 'PAPEL ARCHIVO',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_2',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_3',
      code: 'PAPEL_REVUELTO',
      level: 'GENERAL',
      name: 'PAPEL REVUELTO',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_3',
      code: 'PAPEL_REVUELTO',
      level: 'COMERCIAL',
      name: 'PAPEL REVUELTO',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_3',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_4',
      code: 'ORDINARIO_DE_PRIMERA_ENTREGADO',
      level: 'GENERAL',
      name: 'ORDINARIO DE PRIMERA ENTREGADO',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_4',
      code: 'ORDINARIO_DE_PRIMERA_ENTREGADO',
      level: 'COMERCIAL',
      name: 'ORDINARIO DE PRIMERA ENTREGADO',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_4',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_5',
      code: 'PACA_DE_PRIMERA',
      level: 'GENERAL',
      name: 'PACA DE PRIMERA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_5',
      code: 'PACA_DE_PRIMERA',
      level: 'COMERCIAL',
      name: 'PACA DE PRIMERA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_5',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_6',
      code: 'REBABA',
      level: 'GENERAL',
      name: 'REBABA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_6',
      code: 'REBABA',
      level: 'COMERCIAL',
      name: 'REBABA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_6',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_7',
      code: 'RETORNO_INDUSTRIAL',
      level: 'GENERAL',
      name: 'RETORNO INDUSTRIAL',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_7',
      code: 'RETORNO_INDUSTRIAL',
      level: 'COMERCIAL',
      name: 'RETORNO INDUSTRIAL',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_7',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_8',
      code: 'RETORNO_INDUSTRIAL_ALTO_RESIDUAL',
      level: 'GENERAL',
      name: 'RETORNO INDUSTRIAL ALTO RESIDUAL',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_8',
      code: 'RETORNO_INDUSTRIAL_ALTO_RESIDUAL',
      level: 'COMERCIAL',
      name: 'RETORNO INDUSTRIAL ALTO RESIDUAL',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_8',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_9',
      code: 'RETORNO_INDUSTRIAL_PARA_PROCESAR',
      level: 'GENERAL',
      name: 'RETORNO INDUSTRIAL PARA PROCESAR',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_9',
      code: 'RETORNO_INDUSTRIAL_PARA_PROCESAR',
      level: 'COMERCIAL',
      name: 'RETORNO INDUSTRIAL PARA PROCESAR',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_9',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_10',
      code: 'PLACA_Y_ESTRUCTURA_LARGA',
      level: 'GENERAL',
      name: 'PLACA Y ESTRUCTURA LARGA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_10',
      code: 'PLACA_Y_ESTRUCTURA_LARGA',
      level: 'COMERCIAL',
      name: 'PLACA Y ESTRUCTURA LARGA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_10',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_11',
      code: 'PESADO',
      level: 'GENERAL',
      name: 'PESADO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_11',
      code: 'PESADO',
      level: 'COMERCIAL',
      name: 'PESADO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_11',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_12',
      code: 'PESADO_LARGO',
      level: 'GENERAL',
      name: 'PESADO LARGO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_12',
      code: 'PESADO_LARGO',
      level: 'COMERCIAL',
      name: 'PESADO LARGO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_12',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_13',
      code: 'MIXTO',
      level: 'GENERAL',
      name: 'MIXTO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_13',
      code: 'MIXTO',
      level: 'COMERCIAL',
      name: 'MIXTO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_13',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_14',
      code: 'MIXTO_PARA_PROCESAR',
      level: 'GENERAL',
      name: 'MIXTO PARA PROCESAR',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_14',
      code: 'MIXTO_PARA_PROCESAR',
      level: 'COMERCIAL',
      name: 'MIXTO PARA PROCESAR',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_14',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_15',
      code: 'PACA_DE_SEGUNDA',
      level: 'GENERAL',
      name: 'PACA DE SEGUNDA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_15',
      code: 'PACA_DE_SEGUNDA',
      level: 'COMERCIAL',
      name: 'PACA DE SEGUNDA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_15',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_16',
      code: 'BOTE',
      level: 'GENERAL',
      name: 'BOTE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_16',
      code: 'BOTE',
      level: 'COMERCIAL',
      name: 'BOTE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_16',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_17',
      code: 'PLACA_Y_ESTRUCTURA',
      level: 'GENERAL',
      name: 'PLACA Y ESTRUCTURA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_17',
      code: 'PLACA_Y_ESTRUCTURA',
      level: 'COMERCIAL',
      name: 'PLACA Y ESTRUCTURA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_17',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_18',
      code: 'SERVICIO_DE_RECOLECCION_DE_BASURA',
      level: 'GENERAL',
      name: 'SERVICIO DE RECOLECCION DE BASURA',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_18',
      code: 'SERVICIO_DE_RECOLECCION_DE_BASURA',
      level: 'COMERCIAL',
      name: 'SERVICIO DE RECOLECCION DE BASURA',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_18',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_19',
      code: 'CHATARRA',
      level: 'GENERAL',
      name: 'CHATARRA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_19',
      code: 'CHATARRA',
      level: 'COMERCIAL',
      name: 'CHATARRA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_19',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_20',
      code: 'RETORNO_INDUSTRIAL_ESPECIAL',
      level: 'GENERAL',
      name: 'RETORNO INDUSTRIAL ESPECIAL',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_20',
      code: 'RETORNO_INDUSTRIAL_ESPECIAL',
      level: 'COMERCIAL',
      name: 'RETORNO INDUSTRIAL ESPECIAL',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_20',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_21',
      code: 'FLETE',
      level: 'GENERAL',
      name: 'FLETE',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_21',
      code: 'FLETE',
      level: 'COMERCIAL',
      name: 'FLETE',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_21',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_22',
      code: 'ORDINARIO_DE_PRIMERA',
      level: 'GENERAL',
      name: 'ORDINARIO DE PRIMERA',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_22',
      code: 'ORDINARIO_DE_PRIMERA',
      level: 'COMERCIAL',
      name: 'ORDINARIO DE PRIMERA',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_22',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_23',
      code: 'BASURA',
      level: 'GENERAL',
      name: 'BASURA',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_23',
      code: 'BASURA',
      level: 'COMERCIAL',
      name: 'BASURA',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_23',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_24',
      code: 'ACERO',
      level: 'GENERAL',
      name: 'ACERO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_24',
      code: 'ACERO',
      level: 'COMERCIAL',
      name: 'ACERO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_24',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_25',
      code: 'CARTON_NACIONAL',
      level: 'GENERAL',
      name: 'CARTON NACIONAL',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_25',
      code: 'CARTON_NACIONAL',
      level: 'COMERCIAL',
      name: 'CARTON NACIONAL',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_25',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_26',
      code: 'FIERRO_VACIADO',
      level: 'GENERAL',
      name: 'FIERRO VACIADO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_26',
      code: 'FIERRO_VACIADO',
      level: 'COMERCIAL',
      name: 'FIERRO VACIADO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_26',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_27',
      code: 'PRESTAMO',
      level: 'GENERAL',
      name: 'PRESTAMO',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_27',
      code: 'PRESTAMO',
      level: 'COMERCIAL',
      name: 'PRESTAMO',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_27',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_28',
      code: 'MIXTO_PACA',
      level: 'GENERAL',
      name: 'MIXTO PACA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_28',
      code: 'MIXTO_PACA',
      level: 'COMERCIAL',
      name: 'MIXTO PACA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_28',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_29',
      code: 'PESADO_PLACA',
      level: 'GENERAL',
      name: 'PESADO PLACA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_29',
      code: 'PESADO_PLACA',
      level: 'COMERCIAL',
      name: 'PESADO PLACA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_29',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_30',
      code: 'PACA',
      level: 'GENERAL',
      name: 'PACA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_30',
      code: 'PACA',
      level: 'COMERCIAL',
      name: 'PACA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_30',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_31',
      code: 'UNICEL',
      level: 'GENERAL',
      name: 'UNICEL',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_31',
      code: 'UNICEL',
      level: 'COMERCIAL',
      name: 'UNICEL',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_31',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_32',
      code: 'MADERA',
      level: 'GENERAL',
      name: 'MADERA',
      unit: 'KG',
      category: 'MADERA',
      family: null,
      generalMaterialId: null,
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_32',
      code: 'MADERA',
      level: 'COMERCIAL',
      name: 'MADERA',
      unit: 'KG',
      category: 'MADERA',
      family: 'MADERA',
      generalMaterialId: 'ma_seed_g_32',
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_33',
      code: 'CARTON_CELANESE',
      level: 'GENERAL',
      name: 'CARTON CELANESE',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_33',
      code: 'CARTON_CELANESE',
      level: 'COMERCIAL',
      name: 'CARTON CELANESE',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_33',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_34',
      code: 'COBRE_1ERA',
      level: 'GENERAL',
      name: 'COBRE 1ERA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_34',
      code: 'COBRE_1ERA',
      level: 'COMERCIAL',
      name: 'COBRE 1ERA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_34',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_35',
      code: 'COBRE_2DA',
      level: 'GENERAL',
      name: 'COBRE 2DA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_35',
      code: 'COBRE_2DA',
      level: 'COMERCIAL',
      name: 'COBRE 2DA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_35',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_36',
      code: 'ALUMINIO_BLANDO',
      level: 'GENERAL',
      name: 'ALUMINIO BLANDO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_36',
      code: 'ALUMINIO_BLANDO',
      level: 'COMERCIAL',
      name: 'ALUMINIO BLANDO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_36',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_37',
      code: 'BRONCE',
      level: 'GENERAL',
      name: 'BRONCE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_37',
      code: 'BRONCE',
      level: 'COMERCIAL',
      name: 'BRONCE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_37',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_38',
      code: 'RADIADOR_DE_ALUMINIO',
      level: 'GENERAL',
      name: 'RADIADOR DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_38',
      code: 'RADIADOR_DE_ALUMINIO',
      level: 'COMERCIAL',
      name: 'RADIADOR DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_38',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_39',
      code: 'RADIADOR_PUNTA_DE_COBRE',
      level: 'GENERAL',
      name: 'RADIADOR PUNTA DE COBRE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_39',
      code: 'RADIADOR_PUNTA_DE_COBRE',
      level: 'COMERCIAL',
      name: 'RADIADOR PUNTA DE COBRE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_39',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_40',
      code: 'BOTE_ALUMINIO',
      level: 'GENERAL',
      name: 'BOTE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_40',
      code: 'BOTE_ALUMINIO',
      level: 'COMERCIAL',
      name: 'BOTE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_40',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_41',
      code: 'TUBO',
      level: 'GENERAL',
      name: 'TUBO',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_41',
      code: 'TUBO',
      level: 'COMERCIAL',
      name: 'TUBO',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_41',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_42',
      code: 'PERFIL_CON_PINTURA',
      level: 'GENERAL',
      name: 'PERFIL CON PINTURA',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_42',
      code: 'PERFIL_CON_PINTURA',
      level: 'COMERCIAL',
      name: 'PERFIL CON PINTURA',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_42',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_43',
      code: 'RIN_GRANDE',
      level: 'GENERAL',
      name: 'RIN GRANDE',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_43',
      code: 'RIN_GRANDE',
      level: 'COMERCIAL',
      name: 'RIN GRANDE',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_43',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_44',
      code: 'RIN_CHICO',
      level: 'GENERAL',
      name: 'RIN CHICO',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_44',
      code: 'RIN_CHICO',
      level: 'COMERCIAL',
      name: 'RIN CHICO',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_44',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_45',
      code: 'COBRE_CANDY',
      level: 'GENERAL',
      name: 'COBRE CANDY',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_45',
      code: 'COBRE_CANDY',
      level: 'COMERCIAL',
      name: 'COBRE CANDY',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_45',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_46',
      code: 'ALUMINIO_MACIZO',
      level: 'GENERAL',
      name: 'ALUMINIO MACIZO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_46',
      code: 'ALUMINIO_MACIZO',
      level: 'COMERCIAL',
      name: 'ALUMINIO MACIZO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_46',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_47',
      code: 'SPRAY',
      level: 'GENERAL',
      name: 'SPRAY',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_47',
      code: 'SPRAY',
      level: 'COMERCIAL',
      name: 'SPRAY',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_47',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_48',
      code: 'ACERO_CON_PINTURA',
      level: 'GENERAL',
      name: 'ACERO CON PINTURA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_48',
      code: 'ACERO_CON_PINTURA',
      level: 'COMERCIAL',
      name: 'ACERO CON PINTURA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_48',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_49',
      code: 'ARCHIVO_BLANCO',
      level: 'GENERAL',
      name: 'ARCHIVO BLANCO',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_49',
      code: 'ARCHIVO_BLANCO',
      level: 'COMERCIAL',
      name: 'ARCHIVO BLANCO',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_49',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_50',
      code: 'FOLLETO_COLOR',
      level: 'GENERAL',
      name: 'FOLLETO COLOR',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_50',
      code: 'FOLLETO_COLOR',
      level: 'COMERCIAL',
      name: 'FOLLETO COLOR',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_50',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_51',
      code: 'MAGAZINE',
      level: 'GENERAL',
      name: 'MAGAZINE',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_51',
      code: 'MAGAZINE',
      level: 'COMERCIAL',
      name: 'MAGAZINE',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_51',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_52',
      code: 'PAPEL_REVUELTO_BLANCO_SELECCION',
      level: 'GENERAL',
      name: 'PAPEL REVUELTO BLANCO SELECCION',
      unit: 'KG',
      category: 'PAPEL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_52',
      code: 'PAPEL_REVUELTO_BLANCO_SELECCION',
      level: 'COMERCIAL',
      name: 'PAPEL REVUELTO BLANCO SELECCION',
      unit: 'KG',
      category: 'PAPEL',
      family: 'PAPEL',
      generalMaterialId: 'ma_seed_g_52',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_53',
      code: 'FOLLETO',
      level: 'GENERAL',
      name: 'FOLLETO',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_53',
      code: 'FOLLETO',
      level: 'COMERCIAL',
      name: 'FOLLETO',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_53',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_54',
      code: 'PACA_LARGA',
      level: 'GENERAL',
      name: 'PACA LARGA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_54',
      code: 'PACA_LARGA',
      level: 'COMERCIAL',
      name: 'PACA LARGA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_54',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_55',
      code: 'MIXTO_CIZALLADO',
      level: 'GENERAL',
      name: 'MIXTO CIZALLADO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_55',
      code: 'MIXTO_CIZALLADO',
      level: 'COMERCIAL',
      name: 'MIXTO CIZALLADO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_55',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_56',
      code: 'PLACA_Y_ESTRUCTURA_CORTA',
      level: 'GENERAL',
      name: 'PLACA Y ESTRUCTURA CORTA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_56',
      code: 'PLACA_Y_ESTRUCTURA_CORTA',
      level: 'COMERCIAL',
      name: 'PLACA Y ESTRUCTURA CORTA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_56',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_57',
      code: 'LENA',
      level: 'GENERAL',
      name: 'LENA',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_57',
      code: 'LENA',
      level: 'COMERCIAL',
      name: 'LENA',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_57',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_58',
      code: 'PLASTICO_DURO',
      level: 'GENERAL',
      name: 'PLASTICO DURO',
      unit: 'KG',
      category: 'PLASTICO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_58',
      code: 'PLASTICO_DURO',
      level: 'COMERCIAL',
      name: 'PLASTICO DURO',
      unit: 'KG',
      category: 'PLASTICO',
      family: 'PLASTICO',
      generalMaterialId: 'ma_seed_g_58',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_59',
      code: 'PLASTICO',
      level: 'GENERAL',
      name: 'PLASTICO',
      unit: 'KG',
      category: 'PLASTICO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_59',
      code: 'PLASTICO',
      level: 'COMERCIAL',
      name: 'PLASTICO',
      unit: 'KG',
      category: 'PLASTICO',
      family: 'PLASTICO',
      generalMaterialId: 'ma_seed_g_59',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_60',
      code: 'TARIMAS',
      level: 'GENERAL',
      name: 'TARIMAS',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_60',
      code: 'TARIMAS',
      level: 'COMERCIAL',
      name: 'TARIMAS',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_60',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_61',
      code: 'GARRAFA',
      level: 'GENERAL',
      name: 'GARRAFA',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_61',
      code: 'GARRAFA',
      level: 'COMERCIAL',
      name: 'GARRAFA',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_61',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_62',
      code: 'BOTE_DE_ALUMINIO',
      level: 'GENERAL',
      name: 'BOTE DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_62',
      code: 'BOTE_DE_ALUMINIO',
      level: 'COMERCIAL',
      name: 'BOTE DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_62',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_63',
      code: 'PLACA_DE_ALUMINIO',
      level: 'GENERAL',
      name: 'PLACA DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_63',
      code: 'PLACA_DE_ALUMINIO',
      level: 'COMERCIAL',
      name: 'PLACA DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_63',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_64',
      code: 'PERFIL',
      level: 'GENERAL',
      name: 'PERFIL',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_64',
      code: 'PERFIL',
      level: 'COMERCIAL',
      name: 'PERFIL',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_64',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_65',
      code: 'ALUMINIO_RIN_CHICO',
      level: 'GENERAL',
      name: 'ALUMINIO RIN CHICO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_65',
      code: 'ALUMINIO_RIN_CHICO',
      level: 'COMERCIAL',
      name: 'ALUMINIO RIN CHICO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_65',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_66',
      code: 'ALUMIIO_PISTON',
      level: 'GENERAL',
      name: 'ALUMIIO PISTON',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_66',
      code: 'ALUMIIO_PISTON',
      level: 'COMERCIAL',
      name: 'ALUMIIO PISTON',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_66',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_67',
      code: 'ALUMINIO_TUBO',
      level: 'GENERAL',
      name: 'ALUMINIO TUBO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_67',
      code: 'ALUMINIO_TUBO',
      level: 'COMERCIAL',
      name: 'ALUMINIO TUBO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_67',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_68',
      code: 'RIN_DE_ALUMINIO',
      level: 'GENERAL',
      name: 'RIN DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_68',
      code: 'RIN_DE_ALUMINIO',
      level: 'COMERCIAL',
      name: 'RIN DE ALUMINIO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_68',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_69',
      code: 'COBRE_DE_PRIMERA',
      level: 'GENERAL',
      name: 'COBRE DE PRIMERA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_69',
      code: 'COBRE_DE_PRIMERA',
      level: 'COMERCIAL',
      name: 'COBRE DE PRIMERA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_69',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_70',
      code: 'COBRE_DE_SEGUNDA',
      level: 'GENERAL',
      name: 'COBRE DE SEGUNDA',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_70',
      code: 'COBRE_DE_SEGUNDA',
      level: 'COMERCIAL',
      name: 'COBRE DE SEGUNDA',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_70',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_71',
      code: 'BRONCE_DE_MANGANESO',
      level: 'GENERAL',
      name: 'BRONCE DE MANGANESO',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_71',
      code: 'BRONCE_DE_MANGANESO',
      level: 'COMERCIAL',
      name: 'BRONCE DE MANGANESO',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_71',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_72',
      code: 'RADIADOR_LATON',
      level: 'GENERAL',
      name: 'RADIADOR LATON',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_72',
      code: 'RADIADOR_LATON',
      level: 'COMERCIAL',
      name: 'RADIADOR LATON',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_72',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_73',
      code: 'ALUMINIO_TRASTE',
      level: 'GENERAL',
      name: 'ALUMINIO TRASTE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_73',
      code: 'ALUMINIO_TRASTE',
      level: 'COMERCIAL',
      name: 'ALUMINIO TRASTE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_73',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_74',
      code: 'CAPLE',
      level: 'GENERAL',
      name: 'CAPLE',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_74',
      code: 'CAPLE',
      level: 'COMERCIAL',
      name: 'CAPLE',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_74',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_75',
      code: 'CARTON_AMERICANO',
      level: 'GENERAL',
      name: 'CARTON AMERICANO',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_75',
      code: 'CARTON_AMERICANO',
      level: 'COMERCIAL',
      name: 'CARTON AMERICANO',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_75',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_76',
      code: 'CARTON_NACIONAL_EN_PACAS',
      level: 'GENERAL',
      name: 'CARTON NACIONAL EN PACAS',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_76',
      code: 'CARTON_NACIONAL_EN_PACAS',
      level: 'COMERCIAL',
      name: 'CARTON NACIONAL EN PACAS',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_76',
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_77',
      code: 'CARTON_LIMPIO',
      level: 'GENERAL',
      name: 'CARTON LIMPIO',
      unit: 'KG',
      category: 'CARTON',
      family: null,
      generalMaterialId: null,
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_77',
      code: 'CARTON_LIMPIO',
      level: 'COMERCIAL',
      name: 'CARTON LIMPIO',
      unit: 'KG',
      category: 'CARTON',
      family: 'CARTON',
      generalMaterialId: 'ma_seed_g_77',
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_78',
      code: 'REBABA_DE_BRONCE',
      level: 'GENERAL',
      name: 'REBABA DE BRONCE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_78',
      code: 'REBABA_DE_BRONCE',
      level: 'COMERCIAL',
      name: 'REBABA DE BRONCE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_78',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_79',
      code: 'ACERO_TRASTE',
      level: 'GENERAL',
      name: 'ACERO TRASTE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_79',
      code: 'ACERO_TRASTE',
      level: 'COMERCIAL',
      name: 'ACERO TRASTE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_79',
      active: true,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_80',
      code: 'CANDY',
      level: 'GENERAL',
      name: 'CANDY',
      unit: 'KG',
      category: 'OTRO',
      family: null,
      generalMaterialId: null,
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_80',
      code: 'CANDY',
      level: 'COMERCIAL',
      name: 'CANDY',
      unit: 'KG',
      category: 'OTRO',
      family: 'OTRO',
      generalMaterialId: 'ma_seed_g_80',
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_g_81',
      code: 'RADIADOR_DE_COBRE',
      level: 'GENERAL',
      name: 'RADIADOR DE COBRE',
      unit: 'KG',
      category: 'METAL',
      family: null,
      generalMaterialId: null,
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
    MayoreoCatalogMaterialRecord(
      id: 'ma_seed_c_81',
      code: 'RADIADOR_DE_COBRE',
      level: 'COMERCIAL',
      name: 'RADIADOR DE COBRE',
      unit: 'KG',
      category: 'METAL',
      family: 'METAL',
      generalMaterialId: 'ma_seed_g_81',
      active: false,
      notes: 'IMPORTADO DESDE V_PRECIOS_REPORTE',
    ),
  ],
  prices: <MayoreoCatalogPriceRecord>[
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_1',
      companyId: 'co_seed_1',
      materialId: 'ma_seed_c_1',
      amount: 2.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_2',
      companyId: 'co_seed_1',
      materialId: 'ma_seed_c_2',
      amount: 5.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_3',
      companyId: 'co_seed_1',
      materialId: 'ma_seed_c_3',
      amount: 3.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_4',
      companyId: 'co_seed_1',
      materialId: 'ma_seed_c_4',
      amount: 3.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_5',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_5',
      amount: 5.77,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_6',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_6',
      amount: 4.77,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_7',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_7',
      amount: 5.77,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_8',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_8',
      amount: 5.17,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_9',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_9',
      amount: 5.62,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_10',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_10',
      amount: 5.27,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_11',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_11',
      amount: 5.07,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_12',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_12',
      amount: 4.97,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_13',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_13',
      amount: 4.97,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_14',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_14',
      amount: 4.87,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_15',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_15',
      amount: 3.37,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_16',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_16',
      amount: 4.37,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_17',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_17',
      amount: 5.47,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_18',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_18',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_19',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_19',
      amount: 5.65,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_20',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_20',
      amount: 6.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_21',
      companyId: 'co_seed_2',
      materialId: 'ma_seed_c_21',
      amount: 0.35,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_22',
      companyId: 'co_seed_3',
      materialId: 'ma_seed_c_6',
      amount: 5.5,
      active: true,
      notes:
          'sube .20 el 3/02/26-sube .20 el 19/02/26-SUBE .10 3/03/26-baja .40 el 10-03-26-baja .40 el 19/03/26-baja .40 24/03/26-14/04/26 SUBE A 5.50',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_23',
      companyId: 'co_seed_4',
      materialId: 'ma_seed_c_13',
      amount: 5.5,
      active: true,
      notes: '14/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_24',
      companyId: 'co_seed_5',
      materialId: 'ma_seed_c_22',
      amount: 2.6,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_25',
      companyId: 'co_seed_5',
      materialId: 'ma_seed_c_1',
      amount: 3.8,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_26',
      companyId: 'co_seed_6',
      materialId: 'ma_seed_c_22',
      amount: 2.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_27',
      companyId: 'co_seed_6',
      materialId: 'ma_seed_c_1',
      amount: 2.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_28',
      companyId: 'co_seed_7',
      materialId: 'ma_seed_c_23',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_29',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_24',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_30',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_25',
      amount: 2.7,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_31',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_22',
      amount: 2.4,
      active: true,
      notes: 'baja .20 el 3/02/26-baja .30 el  16/02/26-baja .30 el 23/02/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_32',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_5',
      amount: 6.7,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-ssube .20 el 3/02/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_33',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_6',
      amount: 4.9,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_34',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_7',
      amount: 6.7,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_35',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_8',
      amount: 6.1,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_36',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_9',
      amount: 6.55,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_37',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_13',
      amount: 6.1,
      active: true,
      notes:
          'sube .25 el 13/1/26-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_38',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_11',
      amount: 6.2,
      active: true,
      notes:
          'sube .25 el 13/01/06-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_39',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_16',
      amount: 5.5,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_40',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_17',
      amount: 6.3,
      active: true,
      notes:
          'sube . 25 el 13/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_41',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_14',
      amount: 6.0,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/01/26-sube .20 el 3/02/26- baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_42',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_15',
      amount: 5.8,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .10 el 19/1/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/06/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_43',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_10',
      amount: 6.2,
      active: true,
      notes:
          'sube .25 el 13/01/26-sube .20 el 3/02/26-baja .40 el 16/03/26-23/03/26-baja .40 el 6/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_44',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_12',
      amount: 6.5,
      active: true,
      notes: '19/01/26-23/03/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_45',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_26',
      amount: 4.65,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_46',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_27',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_47',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_28',
      amount: 5.1,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_48',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_29',
      amount: 5.4,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_49',
      companyId: 'co_seed_8',
      materialId: 'ma_seed_c_19',
      amount: 4.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_50',
      companyId: 'co_seed_9',
      materialId: 'ma_seed_c_17',
      amount: 4.8,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_51',
      companyId: 'co_seed_9',
      materialId: 'ma_seed_c_10',
      amount: 4.6,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_52',
      companyId: 'co_seed_9',
      materialId: 'ma_seed_c_11',
      amount: 4.7,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_53',
      companyId: 'co_seed_9',
      materialId: 'ma_seed_c_13',
      amount: 4.6,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_54',
      companyId: 'co_seed_9',
      materialId: 'ma_seed_c_30',
      amount: 4.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_55',
      companyId: 'co_seed_10',
      materialId: 'ma_seed_c_31',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_56',
      companyId: 'co_seed_11',
      materialId: 'ma_seed_c_32',
      amount: 1.65,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_57',
      companyId: 'co_seed_12',
      materialId: 'ma_seed_c_33',
      amount: 2.9,
      active: true,
      notes: 'baja .20 el 6/02/26-BAJA .30 EL 28/02/26-baja .20 el 10/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_58',
      companyId: 'co_seed_12',
      materialId: 'ma_seed_c_25',
      amount: 2.0,
      active: true,
      notes: 'baja .20 el 6/02/26-BAJA EL 28/02/26-baja .10 el 10/04/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_59',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_24',
      amount: 14.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_60',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_34',
      amount: 173.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_61',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_35',
      amount: 182.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_62',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_36',
      amount: 31.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_63',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_37',
      amount: 128.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_64',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_38',
      amount: 30.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_65',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_39',
      amount: 93.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_66',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_40',
      amount: 34.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_67',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_41',
      amount: 31.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_68',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_42',
      amount: 50.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_69',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_43',
      amount: 36.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_70',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_44',
      amount: 53.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_71',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_45',
      amount: 190.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_72',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_46',
      amount: 34.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_73',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_47',
      amount: 46.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_74',
      companyId: 'co_seed_13',
      materialId: 'ma_seed_c_48',
      amount: 11.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_75',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_49',
      amount: 4.7,
      active: true,
      notes: '26/03/26 sube .30 centavos',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_76',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_50',
      amount: 2.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_77',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_51',
      amount: 2.1,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_78',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_52',
      amount: 4.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_79',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_53',
      amount: 2.55,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_80',
      companyId: 'co_seed_14',
      materialId: 'ma_seed_c_21',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_81',
      companyId: 'co_seed_15',
      materialId: 'ma_seed_c_6',
      amount: 4.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_82',
      companyId: 'co_seed_16',
      materialId: 'ma_seed_c_18',
      amount: 9243.89,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_83',
      companyId: 'co_seed_17',
      materialId: 'ma_seed_c_18',
      amount: 6820.8,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_84',
      companyId: 'co_seed_18',
      materialId: 'ma_seed_c_6',
      amount: 6.1,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_85',
      companyId: 'co_seed_19',
      materialId: 'ma_seed_c_15',
      amount: 6.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_86',
      companyId: 'co_seed_19',
      materialId: 'ma_seed_c_13',
      amount: 6.3,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_87',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_15',
      amount: 4.9,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_88',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_54',
      amount: 4.7,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_89',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_13',
      amount: 5.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_90',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_55',
      amount: 5.1,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_91',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_11',
      amount: 5.4,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_92',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_14',
      amount: 4.8,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_93',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_56',
      amount: 5.4,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_94',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_10',
      amount: 5.2,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_95',
      companyId: 'co_seed_20',
      materialId: 'ma_seed_c_6',
      amount: 4.6,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_96',
      companyId: 'co_seed_21',
      materialId: 'ma_seed_c_18',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_97',
      companyId: 'co_seed_22',
      materialId: 'ma_seed_c_57',
      amount: 0.85,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_98',
      companyId: 'co_seed_22',
      materialId: 'ma_seed_c_58',
      amount: 6.4,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_99',
      companyId: 'co_seed_22',
      materialId: 'ma_seed_c_59',
      amount: 3.9,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_100',
      companyId: 'co_seed_22',
      materialId: 'ma_seed_c_60',
      amount: 30.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_101',
      companyId: 'co_seed_22',
      materialId: 'ma_seed_c_61',
      amount: 4.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_102',
      companyId: 'co_seed_23',
      materialId: 'ma_seed_c_31',
      amount: 10.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_103',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_24',
      amount: 17.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_104',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_36',
      amount: 34.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_105',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_62',
      amount: 29.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_106',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_63',
      amount: 25.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_107',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_64',
      amount: 40.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_108',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_38',
      amount: 28.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_109',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_65',
      amount: 42.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_110',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_66',
      amount: 23.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_111',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_67',
      amount: 31.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_112',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_68',
      amount: 43.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_113',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_43',
      amount: 33.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_114',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_69',
      amount: 158.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_115',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_39',
      amount: 72.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_116',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_70',
      amount: 149.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_117',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_37',
      amount: 107.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_118',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_71',
      amount: 102.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_119',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_46',
      amount: 34.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_120',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_72',
      amount: 89.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_121',
      companyId: 'co_seed_24',
      materialId: 'ma_seed_c_73',
      amount: 38.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_122',
      companyId: 'co_seed_25',
      materialId: 'ma_seed_c_74',
      amount: 1.6,
      active: true,
      notes: '9/03/26',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_123',
      companyId: 'co_seed_25',
      materialId: 'ma_seed_c_75',
      amount: 3.3,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_124',
      companyId: 'co_seed_25',
      materialId: 'ma_seed_c_76',
      amount: 2.2,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_125',
      companyId: 'co_seed_25',
      materialId: 'ma_seed_c_77',
      amount: 3.5,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_126',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_24',
      amount: 20.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_127',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_36',
      amount: 23.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_128',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_37',
      amount: 93.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_129',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_70',
      amount: 129.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_130',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_78',
      amount: 70.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_131',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_46',
      amount: 40.5,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_132',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_62',
      amount: 20.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_133',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_64',
      amount: 24.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_134',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_38',
      amount: 23.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_135',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_69',
      amount: 140.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_136',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_79',
      amount: 6.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_137',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_80',
      amount: 210.0,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_138',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_81',
      amount: 40.0,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_139',
      companyId: 'co_seed_26',
      materialId: 'ma_seed_c_44',
      amount: 52.0,
      active: false,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_140',
      companyId: 'co_seed_27',
      materialId: 'ma_seed_c_18',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_141',
      companyId: 'co_seed_28',
      materialId: 'ma_seed_c_60',
      amount: 35.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
    MayoreoCatalogPriceRecord(
      id: 'pr_seed_142',
      companyId: 'co_seed_29',
      materialId: 'ma_seed_c_18',
      amount: 1.0,
      active: true,
      notes: '',
      updatedAt: null,
    ),
  ],
);
