begin;

create temporary table tmp_import_finanzas_companies (
  id text,
  name text,
  source text,
  linked_name text,
  is_active boolean,
  notes text
) on commit drop;

insert into tmp_import_finanzas_companies (
  id,
  name,
  source,
  linked_name,
  is_active,
  notes
) values
  ('fc_import_adt_seguridad', 'ADT SEGURIDAD', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_alonso_montoya', 'ALONSO MONTOYA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_altabrisa_residencial', 'ALTABRISA RESIDENCIAL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_amazon', 'AMAZON', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_american_metal_market', 'AMERICAN METAL MARKET', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_ana_maria_camacho_resendiz', 'ANA MARIA CAMACHO RESENDIZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_att', 'ATT', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_bien_bajado', 'BIEN BAJADO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cargo_prima_de_seguro_empresa', 'CARGO PRIMA DE SEGURO/EMPRESA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_catalina_lopez_estrada_macocel', 'CATALINA LOPEZ ESTRADA (MACOCEL)', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cbicentenario', 'CBICENTENARIO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cecilio_carrera_rodriguez', 'CECILIO CARRERA RODRIGUEZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cesar_gaytan_salas', 'CESAR GAYTAN SALAS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cfe', 'CFE', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cheque_dicsa', 'CHEQUE DICSA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_claudia_sandoval_flores_raloy', 'CLAUDIA SANDOVAL FLORES (RALOY)', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cobro_automatico', 'COBRO AUTOMATICO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_comision_bbva', 'COMISION BBVA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_compensacion_x_retraso', 'COMPENSACION X RETRASO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_cordemex', 'CORDEMEX', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_david_salinas_camare', 'DAVID SALINAS (CAMARE)', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_dep_tercero_host_to_host', 'DEP TERCERO HOST TO HOST', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_dicsa', 'DICSA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_empaques_y_complementos_industriales', 'EMPAQUES Y COMPLEMENTOS INDUSTRIALES', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_extinguidores_zaragoza', 'EXTINGUIDORES ZARAGOZA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_fonacot', 'FONACOT', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_gabriela_vera_hernandez', 'GABRIELA VERA HERNANDEZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_gid_industries', 'GID INDUSTRIES', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_gnp_seguros', 'GNP SEGUROS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_grupo_automotriz_torres_corzo', 'GRUPO AUTOMOTRIZ TORRES CORZO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_grupo_constructor_pate', 'GRUPO CONSTRUCTOR PATE', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_gustavo_rotunno', 'GUSTAVO ROTUNNO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_hacienda_te_devuelve', 'HACIENDA TE DEVUELVE', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_hanwa_steel', 'HANWA STEEL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_hector_uriel_salomon', 'HECTOR URIEL SALOMON', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_hugo_arturo_hernandez_ambris', 'HUGO ARTURO HERNANDEZ AMBRIS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_impuestos_estatales', 'IMPUESTOS ESTATALES', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_impuestos_federales', 'IMPUESTOS FEDERALES', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_impulsora_ambiental_velvel', 'IMPULSORA AMBIENTAL VELVEL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_imss', 'IMSS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_in_focus', 'IN FOCUS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_irma_ruiz_hernandez_heru', 'IRMA RUIZ HERNANDEZ (HERU)', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_iva_com_serv_banca', 'IVA COM SERV BANCA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_iva_comision_bbva', 'IVA COMISION BBVA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_jose_luis_palma_delgado', 'JOSE LUIS PALMA DELGADO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_juan_arellano_rangel', 'JUAN ARELLANO RANGEL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_kenworth_del_bajio', 'KENWORTH DEL BAJIO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_konfio', 'KONFIO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_konfio_pago_terminal', 'KONFIO PAGO TERMINAL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_lub_bajio', 'LUB BAJIO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_luis_pedro_herrera_manriquez', 'LUIS PEDRO HERRERA MANRIQUEZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_ma_magdalena_jimenez_moncada', 'MA MAGDALENA JIMENEZ MONCADA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_maincasa', 'MAINCASA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_maria_alejandra_martinez_araujo', 'MARIA ALEJANDRA MARTINEZ ARAUJO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_maria_de_los_milagros_angeles', 'MARIA DE LOS MILAGROS ANGELES', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_mariana_rodriguez_ramirez', 'MARIANA RODRIGUEZ RAMIREZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_melvar_solutions', 'MELVAR SOLUTIONS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_microsoft', 'MICROSOFT', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_miguel_angel_mendoza_barajas', 'MIGUEL ANGEL MENDOZA BARAJAS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_monica_chavez', 'MONICA CHAVEZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_nomina', 'NOMINA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_opresa', 'OPRESA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_paccar_financial', 'PACCAR FINANCIAL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_pago_flotilla', 'PAGO FLOTILLA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_pago_tarjeta_de_credito', 'PAGO TARJETA DE CREDITO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_pago_vida', 'PAGO VIDA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_pedrial_mazatlan', 'PEDRIAL MAZATLAN', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_petra_morales_gonzalez', 'PETRA MORALES GONZALEZ', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_plasticos_de_ingenieria_mexicanos', 'PLASTICOS DE INGENIERIA MEXICANOS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_prestamo_konfio', 'PRESTAMO KONFIO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_qualitas_seguros', 'QUALITAS SEGUROS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_recicladora_velvel', 'RECICLADORA VELVEL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_reciclados_2v', 'RECICLADOS 2V', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_reciclados_industriales_vh', 'RECICLADOS INDUSTRIALES VH', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_renta_mazatlan', 'RENTA MAZATLAN', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_ricardo_martin_calixto_sotelo', 'RICARDO MARTIN CALIXTO SOTELO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_ricardo_moreno_arreguin', 'RICARDO MORENO ARREGUIN', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_santiago_felipe_ramirez_zuniga', 'SANTIAGO FELIPE RAMIREZ ZUÑIGA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_sarollantas', 'SAROLLANTAS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_sellos_hidraulicos_y_complementos_ind', 'SELLOS HIDRAULICOS Y COMPLEMENTOS IND.', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_serindmontacargas', 'SERINDMONTACARGAS', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_servicio_de_banca_digital', 'SERVICIO DE BANCA DIGITAL', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_soluciones_ambientales_taga', 'SOLUCIONES AMBIENTALES TAGA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_sramary', 'SRAMARY', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_tdfa', 'TDFA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_tennencia', 'TENNENCIA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_togo', 'TOGO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_transportes_tseh', 'TRANSPORTES TSEH', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_traspaso_cuenta_cuenta', 'TRASPASO CUENTA-CUENTA', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_vh', 'VH', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10'),
  ('fc_import_virginia_dora_merino', 'VIRGINIA DORA MERINO', 'DIRECTO', null, true, 'IMPORTADO DESDE LEGACY PROVEEDORES PAGOS 2026-06-10');

insert into public.finanzas_catalog_companies (
  id,
  name,
  source,
  linked_name,
  is_active,
  notes
)
select
  src.id,
  src.name,
  src.source,
  src.linked_name,
  src.is_active,
  src.notes
from tmp_import_finanzas_companies src
where not exists (
  select 1
  from public.finanzas_catalog_companies dst
  where upper(dst.name) = upper(src.name)
);

commit;

