import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.DICSA_PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
const user = '00000000-0000-4000-8000-000000000001';
const shipment = '00000000-0000-4000-8000-000000000002';
const viewer = '00000000-0000-4000-8000-000000000003';
const id = n => `00000000-0000-4000-9000-${String(n).padStart(12,'0')}`;
await db.exec(`
  create role authenticated; create role anon; create schema auth;
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  grant usage on schema auth to authenticated;
  create table profiles(user_id uuid primary key,role text,is_active boolean);
  insert into profiles values('${user}','direccion',true),('${viewer}','viewer',true);
  create table direction_shipment_plans(id uuid primary key,ship_date date,client_name text,planning_material_code text,planned_units integer,priority text,status text,quantity_unit text);
  create table direction_production_capacity_impacts(machine_key text,start_date date,end_date date,impact_percent integer,is_active boolean);
  insert into direction_shipment_plans values('${shipment}','2026-09-14','SAN PABLO','PACA_NACIONAL',40,'normal','confirmado','PACAS');
`);
await db.exec(await readFile(new URL('../supabase/migrations/20260915100000_create_direction_operating_programs.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
const materials = ['PACA_NACIONAL','PACA_LIMPIA','PACA_AMERICANA'];
const conditions = {daily_capacity:100,day_share:50,yard:Object.fromEntries(materials.map(m=>[m,0])),days:Array.from({length:5},()=>({working:true,day_available:true,night_available:true,loss_percent:0,machinery_note:''}))};
conditions.production_history = {start:'2026-08-03',end:'2026-09-13',observed_weeks:['2026-09-07'],record_count:1,legacy_record_count:0,unknown_shift_count:0,totals:[{day_index:0,shift:'DAY',material_code:'PACA_NACIONAL',quantity:40}]};
const shipments = [{id:shipment,date:'2026-09-14',destination:'SAN PABLO',material:'PACA_NACIONAL',quantity:40,priority:'normal'}];
const lines = Array.from({length:5},(_,day_index)=>['DAY','NIGHT'].flatMap(shift=>materials.map(material_code=>({day_index,shift,material_code,quantity:day_index===0&&shift==='DAY'&&material_code==='PACA_NACIONAL'?40:0})))).flat();
const save = async(n,version,c=conditions,s=shipments,l=lines) => (await db.query('select direction_save_operating_program($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb) as p',[id(n),'2026-09-14',version,JSON.stringify(c),JSON.stringify(s),JSON.stringify(l)])).rows[0].p;
const approve = async(n,execute=false) => (await db.query('select direction_approve_operating_program($1,$2) as p',[id(n),execute])).rows[0].p;
let p = await save(1,0);
assert.equal(p.version,1); assert.equal(p.lines.length,30); assert.equal(p.status,'draft');
assert.deepEqual(p.conditions.production_history,conditions.production_history,'historical reference survives save');
assert.equal((await save(1,0)).version,1,'idempotent retry');
await assert.rejects(()=>save(1,0,conditions,shipments,lines.map(l=>({...l,quantity:0}))),/Identificador/);
await assert.rejects(()=>save(2,0),e=>e.code==='PT409');
await assert.rejects(()=>save(2,1,{...conditions,daily_capacity:0}),/Condiciones/);
await assert.rejects(()=>save(2,1,conditions,shipments,lines.slice(1)),/30 celdas/);
assert.equal((await db.query('select count(*)::int as n from direction_operating_programs')).rows[0].n,1,'failed transactions rolled back');
p = await approve(1); assert.equal(p.status,'approved'); assert.equal(p.is_operational,true);
assert.deepEqual(p.conditions.production_history,conditions.production_history,'approval preserves frozen historical reference');
await assert.rejects(()=>db.query('update direction_operating_program_lines set quantity=0 where program_id=$1',[id(1)]),e=>e.code==='42501');
await assert.rejects(()=>db.query('delete from direction_operating_programs where id=$1',[id(1)]),e=>e.code==='42501');
p = await approve(1,true); assert.equal(p.status,'executing');
const late = lines.map(l=>({...l,quantity:l.day_index===0&&l.shift==='NIGHT'&&l.material_code==='PACA_NACIONAL'?40:0}));
await save(2,1,conditions,shipments,late);
await assert.rejects(()=>approve(2),/Faltante/);
const blocked = {...conditions,days:conditions.days.map((d,i)=>({...d,working:i!==0}))};
await save(3,2,blocked);
await assert.rejects(()=>approve(3),/turno bloqueado/);
await save(4,3);
p = await approve(4); assert.equal(p.is_operational,true);
const versions = (await db.query('select version,status,is_operational from direction_operating_programs order by version')).rows;
assert.equal(versions.length,4); assert.equal(versions[0].status,'executing'); assert.equal(versions[0].is_operational,false);
await assert.rejects(()=>approve(1,true),/versión operativa/);
await save(5,4);
await db.exec(`reset role; update direction_shipment_plans set planned_units=41; set role authenticated;`);
await assert.rejects(()=>approve(5),e=>e.code==='PT409');
await assert.rejects(()=>save(6,5),e=>e.code==='PT409');
await db.exec(`reset role; update direction_shipment_plans set planned_units=40;
  insert into direction_production_capacity_impacts values('c1','2026-09-14','2026-09-14',100,true); set role authenticated;`);
await assert.rejects(()=>approve(5),e=>e.code==='PT409');
await assert.rejects(()=>save(6,5),e=>e.code==='PT409');
await db.exec(`select set_config('request.jwt.claim.sub','${viewer}',false);`);
assert.equal((await db.query('select count(*)::int as n from direction_operating_programs')).rows[0].n,0,'RLS excludes unauthorized viewers');
await assert.rejects(()=>save(6,5),e=>e.code==='42501');
await assert.rejects(()=>approve(5),e=>e.code==='42501');
console.log('Operating program SQL: atomic versions, immutable lines, approvals, deadlines, capacity, stale input, permissions passed.');
await db.close();
