do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'maintenance_purchase_order_status'
  ) then
    create type public.maintenance_purchase_order_status as enum (
      'draft',
      'pending_direction',
      'authorized',
      'rejected'
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'maintenance_purchase_line_type'
  ) then
    create type public.maintenance_purchase_line_type as enum (
      'material',
      'mano_obra',
      'refaccion'
    );
  end if;
end
$$;

create table if not exists public.maintenance_purchase_orders (
  id uuid primary key default gen_random_uuid(),
  serial_no bigint generated by default as identity,
  folio text generated always as ('OCM-' || lpad(serial_no::text, 6, '0')) stored,
  order_date date not null default current_date,
  target_label text not null,
  quote_vendor_name text,
  quote_vendor_type text,
  quote_contact text,
  notes text,
  status public.maintenance_purchase_order_status not null default 'draft',
  requested_by uuid,
  requested_by_name text,
  requested_at timestamptz not null default now(),
  direction_authorized_by uuid,
  direction_authorized_by_name text,
  direction_authorized_at timestamptz,
  direction_rejected_at timestamptz,
  direction_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (serial_no),
  unique (folio)
);

create table if not exists public.maintenance_purchase_order_lines (
  id uuid primary key default gen_random_uuid(),
  purchase_order_id uuid not null references public.maintenance_purchase_orders(id) on delete cascade,
  line_no int not null default 1,
  line_type public.maintenance_purchase_line_type not null default 'material',
  qty numeric(12,3),
  unit text,
  description text not null,
  amount numeric(12,2),
  line_total numeric(12,2),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.maintenance_materials
  add column if not exists purchase_order_id uuid references public.maintenance_purchase_orders(id) on delete set null,
  add column if not exists purchase_order_line_id uuid references public.maintenance_purchase_order_lines(id) on delete set null,
  add column if not exists purchase_order_folio text,
  add column if not exists purchase_order_line_description text;

create index if not exists maintenance_purchase_orders_status_idx
  on public.maintenance_purchase_orders (status);
create index if not exists maintenance_purchase_orders_order_date_idx
  on public.maintenance_purchase_orders (order_date desc);
create index if not exists maintenance_purchase_orders_target_label_idx
  on public.maintenance_purchase_orders (target_label);
create index if not exists maintenance_purchase_order_lines_order_idx
  on public.maintenance_purchase_order_lines (purchase_order_id, line_no);
create index if not exists maintenance_materials_purchase_order_idx
  on public.maintenance_materials (purchase_order_id, purchase_order_line_id);

drop trigger if exists trg_set_maintenance_purchase_orders_updated_at
  on public.maintenance_purchase_orders;
create trigger trg_set_maintenance_purchase_orders_updated_at
before update on public.maintenance_purchase_orders
for each row
execute function public.set_maintenance_updated_at();

drop trigger if exists trg_set_maintenance_purchase_order_lines_updated_at
  on public.maintenance_purchase_order_lines;
create trigger trg_set_maintenance_purchase_order_lines_updated_at
before update on public.maintenance_purchase_order_lines
for each row
execute function public.set_maintenance_updated_at();

create or replace view public.v_maintenance_authorized_purchase_order_lines as
select
  pol.id as purchase_order_line_id,
  po.id as purchase_order_id,
  po.folio,
  po.order_date,
  po.target_label,
  po.quote_vendor_name,
  po.quote_vendor_type,
  pol.line_no,
  pol.line_type,
  pol.qty,
  pol.unit,
  pol.description,
  pol.amount,
  coalesce(
    pol.line_total,
    coalesce(pol.qty, 0) * coalesce(pol.amount, 0)
  ) as line_total,
  pol.notes
from public.maintenance_purchase_order_lines pol
join public.maintenance_purchase_orders po
  on po.id = pol.purchase_order_id
where po.status = 'authorized';

alter table public.maintenance_purchase_orders enable row level security;
alter table public.maintenance_purchase_order_lines enable row level security;

grant select, insert, update, delete
  on public.maintenance_purchase_orders
  to authenticated;
grant select, insert, update, delete
  on public.maintenance_purchase_order_lines
  to authenticated;
grant select
  on public.v_maintenance_authorized_purchase_order_lines
  to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'maintenance_purchase_orders'
      and policyname = 'maintenance_purchase_orders_authenticated_all'
  ) then
    create policy maintenance_purchase_orders_authenticated_all
      on public.maintenance_purchase_orders
      for all
      to authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'maintenance_purchase_order_lines'
      and policyname = 'maintenance_purchase_order_lines_authenticated_all'
  ) then
    create policy maintenance_purchase_order_lines_authenticated_all
      on public.maintenance_purchase_order_lines
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end
$$;
