create table if not exists public.operation_directory_contacts (
  id uuid primary key default gen_random_uuid(),
  serial_no bigint generated by default as identity,
  name text not null,
  area text,
  specialty text,
  availability text,
  contact text,
  location text,
  quotes bool not null default true,
  visit_cost numeric(12,2),
  warranty text,
  comments text,
  active bool not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists operation_directory_contacts_name_idx
  on public.operation_directory_contacts (name);

create index if not exists operation_directory_contacts_area_idx
  on public.operation_directory_contacts (area);

create index if not exists operation_directory_contacts_specialty_idx
  on public.operation_directory_contacts (specialty);

create index if not exists operation_directory_contacts_active_idx
  on public.operation_directory_contacts (active);

drop trigger if exists trg_set_operation_directory_contacts_updated_at
  on public.operation_directory_contacts;
create trigger trg_set_operation_directory_contacts_updated_at
before update on public.operation_directory_contacts
for each row
execute function public.set_maintenance_updated_at();

alter table public.operation_directory_contacts enable row level security;

grant select, insert, update, delete
  on public.operation_directory_contacts
  to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'operation_directory_contacts'
      and policyname = 'operation_directory_contacts_authenticated_all'
  ) then
    create policy operation_directory_contacts_authenticated_all
      on public.operation_directory_contacts
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end
$$;
